name: Publish MindSpore OpenAI Competible Server Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Publish Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: infmonkeys/mindspore-openai-competible-server

      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: ./mindspore
          file: ./mindspore/Dockerfile
          push: true
          tags: infmonkeys/mindspore-openai-competible-server:${{ github.ref_name }}-arm
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/arm64

      - name: Save Docker image to a tar file
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}-arm
          docker save infmonkeys/mindspore-openai-competible-server:$RELEASE_TAG -o mindspore-openai-competible-server-$RELEASE_TAG.tar.gz

      - name: Install TOS CLI And Upload to Tos
        env:
          TOS_ACCESS_KEY_ID: ${{ secrets.TOS_ACCESS_KEY_ID }}
          TOS_SECRET_ACCESS_KEY: ${{ secrets.TOS_SECRET_ACCESS_KEY }}
          TOS_REGION: ${{ secrets.TOS_REGION }}
          TOS_ENDPOINT_URL: ${{ secrets.TOS_ENDPOINT_URL }}
          TOS_BUCKET: ${{ secrets.TOS_BUCKET }}
        run: |
          RELEASE_TAG=${GITHUB_REF#refs/tags/}-arm
          wget https://tos-tools.tos-cn-beijing.volces.com/linux/tosutil && chmod a+x tosutil
          ./tosutil config -i "$TOS_ACCESS_KEY_ID" -k "$TOS_SECRET_ACCESS_KEY" -e "$TOS_ENDPOINT_URL" -re "$TOS_REGION" 
          ./tosutil cp mindspore-openai-competible-server-$RELEASE_TAG.tar.gz tos://$TOS_BUCKET/docker/monkeys/mindspore-openai-competible-server/mindspore-openai-competible-server-$RELEASE_TAG.tar.gz
